### ISSUE TITLE
##USER STORY

### ISSUE THREAD

**Issue by angelodrake** [angelodrake/travelgroupie#8]
As a user I want to be able to see my saved events to quickly be able to return and purchase.

##Tasks to complete
- [ ] Login function working

- [ ] Saved events added to slide out menu

- [ ] each even links to event page for that event

**Comment by Simonkcoding** [comment]
-[]able to relate authentication to realtime database to retrieve past records of saved (favorite) event, purchased

**Comment by angelodrake** [comment]
Cool, we are just using this for the class exercise. We are using trello like we normally have been
